mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.system.atom.bean
  config-location: classpath:mybatis-config.xml

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql